/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package StudentDBApp;

public class App {
   

    public static void main(String[] args) {
        Student s1 = new Student();
        s1.enroll();
    }


}
